### ISSUE TITLE
Feature Request for the `Advanced formula environment`: add function (and argument) descriptions to modules as well

### ISSUE THREAD

**Issue by Mo-Gul** [microsoft/Excel-Labs#10]
Would it be possible to add function descriptions to module functions (Modules)  as well as it can be done for "named functions" (Names > Functions)? Maybe this can be done with some sort of special comment like 

```
// @Description("This is a function description.")
```

which has to be placed directly above the function definition.

And maybe something similar can also be done for the functions arguments?

**Comment by jack-williams** [comment]
You should be able to add function descriptions already. Here is a related thread that might be helpful.

https://github.com/microsoft/advanced-formula-environment/issues/61

We do not have support for argument descriptions. A similar request is here: https://github.com/microsoft/advanced-formula-environment/issues/21

Feel free to add any feedback there!

**Comment by Mo-Gul** [comment]
Many thanks for the quick reply and sorry for the noise, because I wasn't aware of the extra repository. (Would I have been able to find it in this repository? If not, maybe add a link somewhere in the `README.md`?)

I'll close this issue here and will look through the issues there if I can find my second feature request there (as well).

**Comment by jack-williams** [comment]
No need to apologise @Mo-gul! 

> Would I have been able to find it in this repository? If not, maybe add a link somewhere in the README.md

Probably not - we should clarify and connect the relationship between to the repositories.

Thanks for your feedback.
