### ISSUE TITLE
Feature Request: "Object" Option in Insert Menu

### ISSUE THREAD

**Issue by richa283** [microsoft/Excel-Labs#16]
Hello Excel-labs team,

I'm writing to propose a minor change in the Excel interface. Currently, in the Insert menu, there's an option labeled "Object." While this feature allows for the insertion of various file types and objects, the term "Object" might not be immediately intuitive for all users.

Can I suggest renaming this option to something more descriptive, such as "File Attachment" or "File Link." These alternatives could potentially enhance user understanding, indicating that this feature allows attaching or linking external files within the Excel sheet.

This change aims to improve user experience, making the feature more accessible and understandable, especially for users who may not be familiar with the term "Object" in this context.

Thank you

**Comment by NWilson** [comment]
Closing. This does not appear to be a request for Excel Labs. If you wish to make suggestions for changes to Excel, please use the feedback icon within Excel, or post on the User Voice forum.
