### ISSUE TITLE
Question: Can you define the Comment for a name via a Gist?

### ISSUE THREAD

**Issue by jonwittwer** [microsoft/Excel-Labs#18]
When compiling LAMBDA functions and sharing via a Gist, is there a syntax (for use in the Gist or when using the AFE module editor) that allows you to define the Description for the named function? The Description is useful because it shows up as a tooltip in Excel.

You can manually edit the Description after importing a Gist. However, for sharing a library of lambda functions, it would be useful to have a way for the Gist to define the Description.

**Comment by jack-williams** [comment]
You can specify the description for a definition within the module syntax using the comments of the form `/** ... */`
```
/**
 * A function that doubles its input
 */
double = LAMBDA(x, x * 2);

/** Another function */
plusOne = LAMBDA(x, x + 1);
```

**Comment by jonwittwer** [comment]
Sorry I wasn't more clear. Instead of "Description" I should have said the "Comment" field in the Name Manager. While is works to have a description within a /* */ comment in Excel Labs, it doesn't add the description into the Comment field within the Name Manager. If the description could be automatically entered into the Comment field, then that description would show up as a tooltip while scrolling through the list of functions that shows up in the Formula Autocomplete box.

**Comment by jack-williams** [comment]
If I understand correctly this should be the case. The text in the module file will be added to the comment field. You need to use `/** */` (note the two `**`).

```
/**
 * The function checks if x and y are the same
 */
aFunction = LAMBDA(x, y, x = y);
```
![image](https://github.com/microsoft/Excel-Labs/assets/4489219/62d4baa1-8b12-4ac7-a915-bb815b71a2c0)


![image](https://github.com/microsoft/Excel-Labs/assets/4489219/f98ed721-672a-4b0c-bea1-233a73b9bf13)

**Comment by jonwittwer** [comment]
Yes! This works perfectly, including multiple lines of comments if needed:

/**
* This examples uses two lines
* for the Comment field.
*/

Thank you! This is exactly what I was looking for. Sorry I didn't notice the use of two ** before.
