### ISSUE TITLE
gpt-4-preview (turbo)

### ISSUE THREAD

**Issue by halueda** [microsoft/Excel-Labs#21]
Recently, a new version of GPT-4 was released:  gpt-4-turbo-preview .
This is gpt-4 but very inexpensive and I would like to use it from excel-labs.

If you have a schedule for this, could you let me know?

**Comment by 4republic** [comment]
I guess they are not supporting this add in ?  too bad

Have you found a decent alternative?

**Comment by jack-williams** [comment]
Closing as we now support the turbo and 4o models. See https://github.com/microsoft/Excel-Labs/issues/29#issuecomment-2343768800
