### ISSUE TITLE
Labs.GenerativeAI #BUSY! error

### ISSUE THREAD

**Issue by preston-johnson** [microsoft/Excel-Labs#3]
Quick note: I'm very excited for the future of this project! Thank you to everyone involved for your continued development.

After updating the AFE to Excel Labs on April 10 and purchasing a Premium OpenAI plan to avoid network throttling for my private key, I still consistently receive a #BUSY! error every time I try to use the formula (and the #N/A error after 30-60 seconds of #BUSY!).

Given that I haven't seen any Troubleshooting steps for this error in the docs I then wondered whether it was a firewall issue, but the #BUSY! error remains even after using the formula through a mobile hotspot connection. (This is admittedly not a conclusive firewall test, but is at least a unique test scenario).

Are there any known fixes to this continuing problem?

**Comment by jack-williams** [comment]
When you hit #N/A, are you able to see the error message? (Usually pops up when hovering over the yellow triangle with !) We have some support for richer errors that are returned from the custom function, and that could help us debug this problem.

**Comment by preston-johnson** [comment]
It appears I only needed to submit my previous comment for new information to arise: my very next attempt to call LABS.GENERATIVEAI() succeeded. Thank you for your guidance!

**Comment by PHWiest** [comment]
Thanks for your post. I, too, have just registered for the $20 monthly fee. Will I be waiting 10 days for activation?  What is the "consumption-based API service? " Is that a Windows Service I need to enable?

**Comment by preston-johnson** [comment]
The $20 fixed monthly premium is for the chat interface [https://chat.openai.com] which is a separate service from the API.

You can generate an API key for your account here:
https://platform.openai.com/account/api-keys

Note that you will need to add another payment method which will be charged according to these rates:
https://openai.com/pricing

**Comment by ks2018ks** [comment]
I have the same issue, but I can't follow this thread.

Under Requirements, it says:
To use the function, you must register an OpenAI account and generate a unique API key.

I have both, but don't understand from the thread here, if this is only a paid for feature.  

If so, then @alison-mk , perhaps you should update the requirements, to make that clear

**Comment by ks2018ks** [comment]
> Yes, the API is a premium feature and requires a method of payment in order to activate the service.

I'm not a paying / premium subscriber or pay as you go account holder, but my account is API key enabled.

In any case, if it needs to be paid for to work, the "requirements" should make that clear
