### ISSUE TITLE
Excel Labs Source Code

### ISSUE THREAD

**Issue by edugca** [microsoft/Excel-Labs#30]
Hi, Guys! I have an R add-in for Excel and I would like to develop an interface such as the one for Python in Excel Labs. As far as I know, Excel Labs source code is open. How can I have access to it?

**Comment by jack-williams** [comment]
Excel Labs is currently closed source and we do not have any plans to open source - I am afraid.

If it is of any help, we built the interface using Monaco + Fluent UI components.
