### ISSUE TITLE
Change LLM

### ISSUE THREAD

**Issue by shrikantsawant** [microsoft/Excel-Labs#36]
Hi
Got a note from OpenAI that Deprecation Reminder: gpt-3.5-turbo-0301, gpt-3.5-turbo-0613, and ​​gpt-3.5-turbo-16k-061.

How do I delete and add new models to the ExcelLabs addin?

S S

**Comment by jack-williams** [comment]
It cannot be done from the add-in by users, but we will be updating the list.

@NWilson

**Comment by shrikantsawant** [comment]
Got a final reminder from OPENAI.Is there an update to list of new models available to the add-in? Any date for the update?





This is a final reminder that the following models will no longer be available starting next Friday, September 13, 2024:
 gpt-3.5-turbo-0301 
 gpt-3.5-turbo-0613
 gpt-3.5-turbo-16k-0613
We have noticed that your organization has recently used at least one of these models. To avoid any disruption, we encourage you to migrate to gpt-4o-mini, our new small model that will give you higher performance at lower cost.

**Comment by jack-williams** [comment]
We've merged an internal change that updates the list, hopefully this will be live soon.

**Comment by shrikantsawant** [comment]
Thank You. Newer models are now reflecting in the addin.
