### ISSUE TITLE
gpt-4 not usable as model?

### ISSUE THREAD

**Issue by FerdinandNathaniel** [microsoft/Excel-Labs#4]
Thanks for bringing out this experiment, incredibly useful. 

I don't currently seem to be able to use gpt-4 as a model for generation (through both the interface and manually inputting it into the command string), even though I do have access to it. I would like to use it for some final fine-tuning of more complex tasks. Currently I have to switch from excel to my own code on the side, but that's just that one extra step we programmers like to get rid off, don't we. 

Is this something easy to fix, or am I doing something wrong?

**Comment by jack-williams** [comment]
> am I doing something wrong

You are not doing anything wrong. We currently do not support GPT-4 completions. I'll add this is a feature enhancement.

**Comment by SherifEldeeb** [comment]
> > am I doing something wrong
> 
> You are not doing anything wrong. We currently do not support GPT-4 completions. I'll add this is a feature enhancement.

We would really appreciate implementing this. any ETA? if the code is available I can work on the necessary code mods

**Comment by ZBZFirst** [comment]
Hi there, I love your add in. I am looking at using it for making question prompts based on pre assigned outcomes. However, 3.5 is terrible for what I am looking to do.

Im looking forward to using GPT4. It is just so much more effective then 3.5.

thank you for doing all this!

**Comment by ZBZFirst** [comment]
Any updates?

**Comment by jack-williams** [comment]
We've been working on this. Tentatively targeting an update next week.

**Comment by ZBZFirst** [comment]
Thank you!

**Comment by jack-williams** [comment]
Now live
