### ISSUE TITLE
Just a Link to ChatGPT?

### ISSUE THREAD

**Issue by PHWiest** [microsoft/Excel-Labs#7]
Hi, 

I am looking for any documentation or impressive demonstrations or techniques using LABS.GENERATIVEAI( ) .

Is this function just a "link" from within a sheet to OpenAI? 
Is there more to it than this? 
Thanks for your help!

**Comment by jack-williams** [comment]
LABS.GENERATIVEAI is just a function that calls the OpenAI text completion API (https://platform.openai.com/docs/api-reference/completions).

The function is low-level, but can be used for some interesting things when combined with prompts and wrapper functions. For example:


```
=LET(
    result, LABS.GENERATIVEAI(
        "Extract all the animals from the text (between <text> tags) and return as a JSON list. The text is <text>" &
            I11 & "</text>"
    ),
    elements, TEXTSPLIT(TEXTBEFORE(TEXTAFTER(result, "["), "]", -1), ","),
    cleaned, MAP(
        elements,
        LAMBDA(element, TEXTBEFORE(TEXTAFTER(TRIM(element), """"), """", -1))
    ),
    cleaned
)
```

![image](https://github.com/microsoft/Excel-Labs/assets/4489219/0cda12d8-c1a8-4678-b3c2-2c311e431c07)

You can also use it for translation, parsing text, sentiment analysis, and so on.

**Comment by PHWiest** [comment]
Thank YOU!

 

Phil
