### ISSUE TITLE
How to install Excel Labs?

### ISSUE THREAD

**Issue by SystemsModelling** [microsoft/Excel-Labs#8]
I posted this on Twitter and the Office 365 techcommunity but maybe here is best:
https://techcommunity.microsoft.com/t5/excel/excel-labs/m-p/3880690

Why can't I install Excel Labs?  Windows 10, 32-bit MS365 Excel version 2306 Current Channel. I get a "deployment error" once it goes to Microsoft 365 Apps for Enterprise, although I am logged in there.
https://admin.microsoft.com/Adminportal/Home#/Settings/IntegratedApps

 

![ExcelLabs](https://github.com/microsoft/Excel-Labs/assets/13900438/9f4c77f9-2597-4f88-95e7-9e8c1151df87)
![DeploymentError](https://github.com/microsoft/Excel-Labs/assets/13900438/e4e149e9-5bf3-4727-8d90-f22765015504)

 I have installed it successfully on a laptop in 64-bit Excel 365.

**Comment by jack-williams** [comment]
Are you able to install other Office store Excel add-ins. Is this specific to Excel Labs?

**Comment by SystemsModelling** [comment]
> Are you able to install other Office store Excel add-ins. Is this specific to Excel Labs?

Jack, the source of the problem was that the link from microsoft.com was incorrect. May I ask you to update this page please:
https://www.microsoft.com/en-us/garage/profiles/excel-labs/
At the top of that page it says:
Available on
[Download from the Web] button links to:
https://appsource.microsoft.com/en-us/product/office/WA200003696?exp=ubp8

which is incorrect.
